# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
     v.memory = 6048
     v.cpus = 2
  end

  config.vm.box_download_insecure = true
  config.vm.box = "bento/centos-7.1"


  (1..3).each do |i|
  	config.vm.define "node#{i}" do |s|
      		s.vm.network "public_network", auto_config: false, ip: "10.1.1.23#{i}", netmask: "255.255.254.0", mac: "5CA1AB1E000#{i}"
		s.vm.provision "shell", run: "always", inline: "ifconfig enp0s8 10.1.1.23#{i} netmask 255.255.254.0 up"
		s.vm.hostname = "sdzyuban-mesos-0#{i}"
      		s.vm.provision :shell, path: "bootstrap.chef.sh"
  	end
  end 
end