# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
     v.memory = 1024
     v.cpus = 1
  end

  config.vm.box = "bento/centos-7.1"
  config.vm.define "node1" do |node1|
      node1.vm.network "public_network", ip: "10.1.0.178", netmask: "255.255.254.0"
      node1.vm.hostname = "sdzyuban-mesos-pc"
      node1.vm.box = "mesos-master"
  end

  config.vm.define "node2" do |node2|
      node2.vm.network "private_network", ip: "192.168.33.11"
      node2.vm.hostname = "sdzyuban-mesos-01"
      config.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "node3" do |node3|
      node3.vm.network "private_network", ip: "192.168.33.12"
      node3.vm.hostname = "sdzyuban-mesos-02"
      config.vm.provision :shell, path: "bootstrap.sh"
  end

  config.vm.define "node4" do |node4|
      node4.vm.network "private_network", ip: "192.168.33.13"
      node4.vm.hostname = "sdzyuban-mesos-03"
      config.vm.provision :shell, path: "bootstrap.sh"
  end
 
end