# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|

  config.vm.provider "virtualbox" do |v|
     v.memory = 1024
     v.cpus = 1
  end

  config.vm.box = "bento/centos-7.1"
  config.vm.define "node" do |node|
      node.vm.network "public_network", netmask:"255.255.240.0"
      node.vm.hostname = "sdzyuban-mesos-01"
      config.vm.provision :shell, path: "bootstrap.sh"
  end
end